
// Objective-C API for talking to the following Go packages
//
//	github.com/quan-to/react-native-pgp/chevronwrap
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Chevronwrap_FRAMEWORK_H__
#define __Chevronwrap_FRAMEWORK_H__

#include "Chevronwrap.objc.h"
#include "Universe.objc.h"

#endif
